# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Francisco Carmona
title: Machine Learning Cloud Engineer
email: jcarmfran@gmail.com
website: www.github.com/jcarmfran

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  jcarmfran
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: francisco-j-carmona
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/ProfilePictureSmall.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Francisco and I'm an established network engineer looking to expand my expertise into machine learning technologies.

  I am most skilled in: <mark>Azure</mark>, <mark>Python</mark>, <mark>Machine Learning</mark>, and <mark>Networking</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microsoft
        link: Microsoft.com
        # link_text: Microsoft.com
        sub_title: Azure Networking Support Engineer
        caption: August 2022 - January 2024
        quote: >
          Empowering our customers to do more.
        description: | # this will include new lines to allow paragraphs
          Provided tier 3 networking support to enterprise customers utilizing Azure services.
      - layout: left
        title: Metronet
        link: Metronet.com
        # link_text: Microsoft.com
        sub_title: Networking Engineer
        caption: May 2020 - July 2022
        quote: >
          Metronet things
        description: | # this will include new lines to allow paragraphs
          Helped in turning up and troubleshooting fiber internet, IP-phone, and POTS lines for business customers.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Handwritten Digits Classifier
        link: github.com/jcarmfran/DS-Portfolio/Neural Networks/HandwrittenDigitsClassifier.ipynb
        link_text: HandwrittenDigitsClassifier.ipynb
        additional_links:
          - title:  jcarmfran/HandwrittenDigitsClassifier
            icon: fab fa-github
            url: github.com/jcarmfran/DS-Portfolio/Neural Networks/HandwrittenDigitsClassifier.ipynb
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An example of a classification model where handwritten digits (digits 0 through 9) are identified. 
        description: | # this will include new lines to allow paragraphs
          Exploring the effectiveness of deep, feed-forward neural networks at classifying images of handwritten digits (digits 0 through 9). I started this project as a way of learning <mark>SciKit-Learn</mark>'s powerful classification modules.  I have learned many skills through this and been I'm very proud of having this in my portfolio.
      - layout: top-middle
        title: [Regression Project]
        link: github.com/jcarmfran/DS-Portfolio/Neural Networks/HandwrittenDigitsClassifier.ipynb
        link_text: [Regression].ipynb
        additional_links:
          - title:  jcarmfran/[Regression]
            icon: fab fa-github
            url: github.com/jcarmfran/DS-Portfolio/Regression/[Regression].ipynb
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An example of a regression model where [context]. 
        description: | # this will include new lines to allow paragraphs
          [Description of project].
      - layout: top-middle
        title: [Deep Learning Project]
        link: github.com/jcarmfran/DS-Portfolio/Deep Learning/Tensorflow/[Deep Learning Project].ipynb
        link_text: [Tensorflow].ipynb
        additional_links:
          - title:  jcarmfran/[Tensorflow]
            icon: fab fa-github
            url: github.com/jcarmfran/DS-Portfolio/Deep Learning/[Tensorflow].ipynb
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An example of a Deep Learning model where <mark>Tensorflow</mark> is used to ... [context]. 
        description: | # this will include new lines to allow paragraphs
          [Description of project] .

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Illinois State University
        caption: 2020 - 2022
        sub_title: BSc Computer Systems Technologies
        quote: >
          Redbirds...caw caw...caw caw
        description: | # this will include new lines to allow paragraphs
          During my time at Illinois State I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and machine learning some of my other interests and hobbies are:
      - Just a being a cool dude
      - Annoying my wife
      - Annoying my newborn baby
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
